#!/bin/sh
set -eu

fail() { printf 'scheduler: %s\n' "$*" >&2; exit 1; }
[ "$#" -ge 3 ] && [ "$#" -le 4 ] || fail 'usage: scheduler.sh enable|disable|status REPO STATE_DIR [--dry-run]'
action=$1
repo=$2
state=$3
dry_run=0
case "$action" in enable|disable|status) ;; *) fail "unknown action: $action";; esac
if [ "$#" -eq 4 ]; then
    [ "$4" = --dry-run ] || fail "unknown option: $4"
    dry_run=1
fi
: "${HOME:?HOME must be set}"
config=${XDG_CONFIG_HOME:-$HOME/.config}
case "$state" in */dotfiles) state_home=${state%/dotfiles};; *) fail 'STATE_DIR must end in /dotfiles';; esac
[ -n "$state_home" ] || state_home=/
carriage_return=$(printf '\r')
for path in "$repo" "$state" "$HOME" "$config" "$state_home"; do
    case "$path" in /*) ;; *) fail 'paths must be absolute';; esac
    case "$path" in *'
'*|*"$carriage_return"*) fail 'newline and carriage-return paths are not supported';; esac
done
scheduler_path=/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin
marker='Generated by dotfiles scripts/scheduler.sh'
label=com.snowykr.dotfiles.update
os=$(uname -s)
case "$os" in
    Darwin)
        command -v launchctl >/dev/null || fail 'launchctl is unavailable'
        domain=gui/$(id -u)
        launchctl print "$domain" >/dev/null 2>/dev/null || fail 'native user launchctl domain is unavailable'
        directory=$HOME/Library/LaunchAgents
        definition=$directory/$label.plist
        ;;
    Linux)
        command -v systemctl >/dev/null || fail 'systemctl is unavailable'
        systemctl --user show-environment >/dev/null 2>/dev/null || fail 'native systemd user manager is unavailable'
        directory=$config/systemd/user
        definition=$directory/dotfiles-update.service
        timer=$directory/dotfiles-update.timer
        ;;
    *) fail "unsupported OS: $os";;
esac

owned() {
    [ ! -L "$1" ] && [ -f "$1" ] && grep -F -x "$marker_line" "$1" >/dev/null
}
case "$os" in Darwin) marker_line="<!-- $marker -->";; Linux) marker_line="# $marker";; esac
check_owned() {
    if [ -e "$1" ] || [ -L "$1" ]; then
        owned "$1" || fail "refusing to modify unmanaged definition: $1"
    fi
}
is_enabled() {
    case "$os" in
        Darwin) launchctl print "$domain/$label" >/dev/null 2>/dev/null;;
        Linux) systemctl --user is-enabled --quiet dotfiles-update.timer >/dev/null 2>/dev/null &&
            systemctl --user is-active --quiet dotfiles-update.timer >/dev/null 2>/dev/null;;
    esac
}
if [ "$action" = status ]; then
    if is_enabled; then printf 'enabled\n'; else printf 'disabled\n'; fi
    exit 0
fi
check_owned "$definition"
[ "$os" != Linux ] || check_owned "$timer"
if [ "$dry_run" -eq 1 ]; then
    printf 'Would %s %s scheduler: /bin/sh %s/maintain.sh update (state: %s)\n' "$action" "$os" "$repo" "$state"
    exit 0
fi
if [ "$action" = disable ]; then
    case "$os" in
        Darwin)
            if [ -f "$definition" ]; then
                if is_enabled; then launchctl bootout "$domain/$label"; fi
                rm -f "$definition"
            fi
            ;;
        Linux)
            if [ -f "$definition" ] || [ -f "$timer" ]; then
                systemctl --user disable --now dotfiles-update.timer
                rm -f "$definition" "$timer"
                systemctl --user daemon-reload
            fi
            ;;
    esac
    printf 'disabled\n'
    exit 0
fi

xml() {
    printf '%s' "$1" | sed -e 's/\&/\&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g' -e 's/"/\&quot;/g' -e "s/'/\&apos;/g"
}
unit_quote() {
    printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/%/%%/g' -e 's/	/\\t/g'
}
exec_quote() { unit_quote "$1" | sed 's/\$/$$/g'; }
mkdir -p "$directory" "$state"
tmp=$(mktemp "$directory/.dotfiles-update.XXXXXX")
trap 'rm -f "$tmp"' EXIT
trap 'exit 129' HUP
trap 'exit 130' INT
trap 'exit 143' TERM
changed=0
install_definition() {
    if [ -f "$1" ] && cmp -s "$tmp" "$1"; then return; fi
    chmod 644 "$tmp"
    mv -f "$tmp" "$1"
    changed=1
    tmp=$(mktemp "$directory/.dotfiles-update.XXXXXX")
}
case "$os" in
    Darwin)
        cat > "$tmp" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
$marker_line
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
<key>Label</key><string>$label</string>
<key>ProgramArguments</key><array><string>/bin/sh</string><string>$(xml "$repo/maintain.sh")</string><string>update</string></array>
<key>EnvironmentVariables</key><dict>
<key>PATH</key><string>$scheduler_path</string>
<key>HOME</key><string>$(xml "$HOME")</string>
<key>XDG_CONFIG_HOME</key><string>$(xml "$config")</string>
<key>XDG_STATE_HOME</key><string>$(xml "$state_home")</string>
</dict>
<key>StartCalendarInterval</key><array>
<dict><key>Minute</key><integer>0</integer></dict>
<dict><key>Minute</key><integer>15</integer></dict>
<dict><key>Minute</key><integer>30</integer></dict>
<dict><key>Minute</key><integer>45</integer></dict>
</array>
<key>StandardOutPath</key><string>$(xml "$state/scheduler.log")</string>
<key>StandardErrorPath</key><string>$(xml "$state/scheduler.log")</string>
</dict></plist>
EOF
        install_definition "$definition"
        if is_enabled; then
            if [ "$changed" -eq 1 ]; then launchctl bootout "$domain/$label"; else printf 'enabled\n'; exit 0; fi
        fi
        launchctl enable "$domain/$label"
        launchctl bootstrap "$domain" "$definition"
        ;;
    Linux)
        cat > "$tmp" <<EOF
$marker_line
[Unit]
Description=Update dotfiles checkout
[Service]
Type=oneshot
TimeoutStartSec=120
Environment="PATH=$scheduler_path"
Environment="HOME=$(unit_quote "$HOME")"
Environment="XDG_CONFIG_HOME=$(unit_quote "$config")"
Environment="XDG_STATE_HOME=$(unit_quote "$state_home")"
ExecStart=/bin/sh "$(exec_quote "$repo/maintain.sh")" update
EOF
        install_definition "$definition"
        cat > "$tmp" <<EOF
$marker_line
[Unit]
Description=Update dotfiles every fifteen minutes
[Timer]
OnCalendar=*-*-* *:0/15:00
Persistent=true
[Install]
WantedBy=timers.target
EOF
        install_definition "$timer"
        if [ "$changed" -eq 1 ]; then systemctl --user daemon-reload; fi
        systemctl --user enable --now dotfiles-update.timer
        if [ "$changed" -eq 1 ]; then systemctl --user restart dotfiles-update.timer; fi
        ;;
esac
is_enabled || fail 'scheduler registration did not become enabled'
printf 'enabled\n'
